### ISSUE TITLE
Feature request: Ability to turn on/ off appropriate modules

### ISSUE THREAD

**Issue by Oriskana** [SceptreOfficial/Simplex-Tools-Extensions#1]
Ability to turn on/ off appropriate modules for example Civilian Populate module. 
Example use case: Players arrive to city, Populate module is activated. Players leave the city, Populate module is deactivated and civies are deleted.

**Comment by SceptreOfficial** [comment]
I added some simple caching support for civilians spawned with the 'populate' module. It can be enabled in the addon options. You can customize the distance from players when they will be spawned in and out. If you have any more suggestions on the matter, let me know. I'll close this issue for now.
27c4d7983302ee21d8b0c460d8627c03af9c9dca
